default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: April_development

test:
  <<: *default
  database: April_test
